theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
auto-pairs = false
rulers = [80, 120]
scrolloff = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = true

